all:
  hosts:
    serveur1_Master   ansible_ssh_port=2224   ansible_host_port=192.168.56.1  ansible_user=vagrant
    serveur2_Slave    ansible_ssh_port=2225   ansible_host_port=192.168.56.1  ansible_user=vagrant
    serveur3_Test     ansible_ssh_port=2226   ansible_host_port=192.168.56.1  ansible_user=vagrant
    serveur4_Prod     ansible_ssh_port=2227   ansible_host_port=192.168.56.1  ansible_user=vagrant
