- name: install release
  become: yes
  yum: 
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present
    
- name: update
  become: yes
  yum:
    name: update
    state: present

- name: install pip et python
  become: yes
  yum: 
    name: [ python36u, python36u-libs, python36u-devel, python36u-pip ]
    state: present
    
- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8081:8080
    state: started
 
